server:
  port: 8092
  shutdown: graceful

spring:
  main:
    banner-mode: off


solace:
  jms:
    host: solace-broker
    msg-vpn: default
    client-username: default
    client-password: default
